---
#
# Installing Filebeat
#

# Create directory for certification
- name: Make new directory for cert
  file:
   path: /etc/pki/tls/certs
   state: directory
   recurse: yes
   mode: '755'

# Download SSL certificate:
- name: Download certificate
  get_url:
    url: https://raw.githubusercontent.com/logzio/public-certificates/master/COMODORSADomainValidationSecureServerCA.crt
    dest: /etc/pki/tls/certs/COMODORSADomainValidationSecureServerCA.crt
    mode: '644'

# Install Filebeat 
- name: Install Filebeat with apt
  apt:
   name: filebeat
   update_cache: yes
 
# Replace Filebeat configuration to ship to Logz.io. 
- name: Replace default filebeat.yml configurations
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml

# Starting Filebeat
- name: Starting Filebeat
  service:
   name: filebeat
   state: restarted
