---
#
# Installing Logstash
#

# Install logstash

- name: Install Logstash with apt
  apt:
   name: logstash
   update_cache: yes
 
# Configurations

- name: Configure filebeat input
  template: src=filebeat-input.conf dest=/etc/logstash/conf.d/filebeat-input.conf

- name: Configure syslog filter
  template: src=syslog-filter.conf dest=/etc/logstash/conf.d/syslog-filter.conf

- name: Configure elasticsearch output
  template: src=elasticsearch-output.conf dest=/etc/logstash/conf.d/elasticsearch-output.conf

# Starting logstash

- name: Starting Logstash
  service:
   name: logstash
   state: restarted
   enabled: yes
