---
#
# Installing Metricbeat
#

# Install Metricbeat 

- name: Install Metricbeat with apt
  apt:
   name: metricbeat
   update_cache: yes

# Update number of shards in config file

- name: Updating the number of shards in config file
  lineinfile:
   destfile: /etc/metricbeat/metricbeat.yml
   regexp: 'index.number_of_shards:'
   line: 'index.number_of_shards: 0'

# Update kibana host in config file

- name: Updating the kibana host in config file
  lineinfile:
   destfile: /etc/metricbeat/metricbeat.yml
   insertafter: 'setup.kibana:'
   line: 'setup.kibana.host: "http://localhost:5601"' 

# Starting Metricbeat

- name: Starting Metricbeat
  service:
   name: metricbeat
   state: restarted
   enabled: yes
