- name: Installing Nginx
  apt:
          name: nginx
          update_cache: yes

- name: Copying config file
  template:
          src: config.j2
          dest: /etc/nginx/sites-available/default

- name: Reload Nginx service
  command: service nginx reload
