---
  - name: Provision an EC2 Instance.
    hosts: local
    connection: local
    gather_facts: False
    tags: provisioning
    # required parameters
    vars:
      instance_type: t3.medium
      security_group: chirag_project_sg
      image: ami-07ebfd5b3428b6f4d
      keypair: your_private_key
      vpc_subnet_id: subnet_id
      region: us-east-1 # Change the Region
      count: 2
 
    # Task that will be used to Launch/Create an EC2 Instance
    tasks:
 
      - name: Create a security group
        local_action: 
          module: ec2_group
          name: "{{ security_group }}"
          description: Chirag SG
          region: "{{ region }}"
          vpc_id: vpc-0b061c711cd6ec803
          rules:
            - proto: tcp
              from_port: 22
              to_port: 22
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: 8080
              to_port: 8080
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: 80
              to_port: 80
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: 443
              to_port: 443
              cidr_ip: 0.0.0.0/0
          rules_egress:
            - proto: all
              cidr_ip: 0.0.0.0/0
        register: basic_firewall
        
      - name: Launching Chirag's new EC2 Instance
        local_action: ec2 
                      group={{ security_group }} 
                      instance_type={{ instance_type}} 
                      image={{ image }} 
                      wait=true
                      wait_timeout=500 
                      region={{ region }}
                      vpc_subnet_id={{ vpc_subnet_id}}
                      keypair={{ keypair }}
                      count={{count}}
                      assign_public_ip=yes
        register: ec2_chirag
 
      - name: Add the newly created EC2 instance(s) to the local host group
        local_action: lineinfile 
                      path=~/MyPlaybooks/drupal-ansible-latest/hosts
                      insertafter="\[web-server\]" 
                      line="{{ item.public_ip }} ansible_user=ubuntu"
        with_items: '{{ec2_chirag.instances}}'
 
      - name: Add new instance to Chirag's host group
        add_host:
          hostname: "{{ item.public_ip }}"
          groupname: launched
        with_items: "{{ ec2_chirag.instances }}"
 
      - name: Let's wait for SSH to come up. Usually that takes ~10 seconds
        local_action: wait_for 
                      host={{ item.public_ip }} 
                      port=22 
                      state=started
        with_items: '{{ ec2_chirag.instances }}'
 
      - name: Add tag to Instance(s)
        local_action: ec2_tag resource={{ item.id }} region={{ region }} state=present
        with_items: '{{ ec2_chirag.instances }}'
        args:
          tags:
            Name: chirag
            owner: chirag
            purpose: project
