---
  - name: Provision an EC2 Instance. Detailed steps by Crunchify.
    hosts: local
    connection: local
    gather_facts: False
    tags: provisioning
    # required parameters
    vars:
      instance_type: t3.medium
      security_group: chirag-project-sg
      image: ami-07ebfd5b3428b6f4d
      keypair: Chirag-Pem
      region: us-east-1 # Change the Region
      count: 1
 
    # Task that will be used to Launch/Create an EC2 Instance
    tasks:
 
      - name: Create a security group
        local_action: 
          module: ec2_group
          name: "{{ security_group }}"
          description: Security Group for Crunchify's EC2 Servers
          region: "{{ region }}"
          rules:
            - proto: tcp
              from_port: 22
              to_port: 22
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: 8080
              to_port: 8080
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: 80
              to_port: 80
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: 443
              to_port: 443
              cidr_ip: 0.0.0.0/0
          rules_egress:
            - proto: all
              cidr_ip: 0.0.0.0/0
        register: basic_firewall
        
      - name: Launching Crunchify's the new EC2 Instance
        local_action: ec2 
                      group={{ security_group }} 
                      instance_type={{ instance_type}} 
                      image={{ image }} 
                      wait=true
                      wait_timeout=500 
                      region={{ region }} 
                      keypair={{ keypair }}
                      count={{count}}
        register: ec2_chirag
 
      - name: Add the newly created EC2 instance(s) to the local host group
        local_action: lineinfile 
                      path=chirag.txt
                      regexp={{ item.public_ip }} 
                      insertafter='\[chhirag\]' line={{ item.public_ip }}
        with_items: '{{ec2_chirag.instances}}'
 
      - name: Add new instance to Chirag's host group
        add_host:
          hostname: "{{ item.public_ip }}"
          groupname: launched
        with_items: "{{ ec2_chirag.instances }}"
 
      - name: Let's wait for SSH to come up. Usually that takes ~10 seconds
        local_action: wait_for 
                      host={{ item.public_ip }} 
                      port=22 
                      state=started
        with_items: '{{ ec2_chirag.instances }}'
 
      - name: Add tag to Instance(s)
        local_action: ec2_tag resource={{ item.id }} region={{ region }} state=present
        with_items: '{{ ec2_chirag.instances }}'
        args:
          tags:
            Name: chirag
            owner: chirag
            purpose: project
